// Generated by CoffeeScript 1.9.0
(function() {
  var Odb, creds, env, envs, odb, odbs, query, sqls, _, _i, _len;

  Odb = require('./index');

  _ = require('lodash');

  envs = {
    medInt: {
      host: '10.229.147.11',
      name: 'pharos'
    },
    avowt: {
      host: 'localhost',
      name: 'avowt'
    },
    medDev: {
      host: '10.229.123.11',
      name: 'pharos'
    },
    accInt: {
      host: '10.229.44.11',
      name: 'pharos',
      logLevel: 2
    },
    accDev: {
      host: '10.229.122.11',
      name: 'pharos'
    }
  };

  creds = {
    admin: {
      username: 'admin',
      password: 'admin'
    },
    reader: {
      username: 'reader',
      password: 'reader'
    },
    writer: {
      username: 'writer',
      password: 'writer'
    },
    subject: {
      username: 'subject1$helius',
      password: 'subject1Pass'
    },
    manager: {
      username: 'admin1$helius',
      password: 'admin1Pass'
    }
  };

  sqls = {
    user: 'select from ouser limit 1'
  };

  env = envs.avowt;

  odbs = [Odb.oweb(env)];

  query = function(db, sql) {
    odb.query(sql, function(err, res) {
      err && console.log(' CALL ERR:', err);
      return res && console.log(' CALL RES:', res);
    });
    return odb.query(sql).then((function(_this) {
      return function(res) {
        return console.log('PROM RES:', res);
      };
    })(this))["catch"]((function(_this) {
      return function(err) {
        return console.log('PROM ERR:', err);
      };
    })(this));
  };

  for (_i = 0, _len = odbs.length; _i < _len; _i++) {
    odb = odbs[_i];
    console.log(odb.opts);
    odb.auth(creds.reader);
    odb.describe('ouser').then(console.log);
  }

}).call(this);
